application:
  application version:
  application loges file full-path:

emails settings:
  users email:
    - user1@example.com
    - user2@example.com
  users email password: # Passwords will be encrypted after initial setting !!
    - password1
    - password2
  target email addresses:
    user1@example.com:
      - target1@example.com
      - target2@example.com
    user2@example.com:
      - target3@example.com
  target email title:
    user1@example.com:
      - title1
      - title2
    user2@example.com:
      - title3

Options:
  receiving email label name: inbox # Default

database:
  host: your-database-host
  port: your-database-port
  username: your-database-username
  password: your-database-password
  database: your-database-name