application:
  applicationVersion: 0.0.0

emailSettings:
  userEmail: userEmail@example.com
  # Passwords will be encrypted after initial setting !!
  userEmailPassword: userEmailPassword-example
  targetEmailAddresses:
    - target1@example.com
    - target2@example.com
    - target3@example.com
  targetEmailTitle:
    - title1
    - title2
    - title3
  properties:
    protocol: imaps
    host: imap.gmail.com
    port: 993

options:
  receivingEmailLabelName:
    - INBOX # Default

database:
  url: jdbc:postgresql://localhost:5432/postgres
  host: your-database-host
  port: 5432
  username: postgres
  password: password
  database: postgresx