application:
  applicationVersion:
  applicationLogFilePath:

emailSettings:
  usersEmail:
    - user1@example.com
    - user2@example.com
  usersEmailPassword: # Passwords will be encrypted after initial setting !!
    - password1
    - password2
  targetEmailAddresses:
    - target1@example.com
    - target2@example.com
    - target3@example.com
  targetEmailTitle:
    - title1
    - title2
    - title3

options:
  receivingEmailLabelName:
    - inbox # Default

database:
  host: your-database-host
  port: your-database-port
  username: your-database-username
  password: your-database-password
  database: your-database-name